# -*- coding: utf-8 -*-
"""Copy of Welcome To Colab

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nucNB46ekA4H2VRdUqWeVm-F10UWfL6m
"""

import streamlit as st
import statistics
import matplotlib.pyplot as plt

st.set_page_config(page_title="Kalkulator Statistik", layout="centered")

st.title("📊 Kalkulator Statistik Sederhana")
st.write("Masukkan data numerik yang dipisahkan dengan koma (,)")

# Input pengguna
data_input = st.text_area("Contoh: 10, 20, 30, 40, 50", height=100)

if st.button("Hitung Statistik"):
    try:
        # Parsing data
        data = [float(item.strip()) for item in data_input.split(",") if item.strip() != ""]

        if len(data) < 2:
            st.warning("Masukkan minimal dua data untuk menghitung statistik.")
        else:
            # Perhitungan statistik
            mean = statistics.mean(data)
            median = statistics.median(data)
            try:
                mode = statistics.mode(data)
            except statistics.StatisticsError:
                mode = "Tidak ada modus tunggal"

            stdev = statistics.stdev(data)
            variance = statistics.variance(data)

            # Menampilkan hasil
            st.subheader("📈 Hasil Statistik")
            st.write(f"Jumlah Data: {len(data)}")
            st.write(f"Mean       : {mean}")
            st.write(f"Median     : {median}")
            st.write(f"Modus      : {mode}")
            st.write(f"Stdev      : {stdev}")
            st.write(f"Variansi   : {variance}")

            # Visualisasi histogram
            st.subheader("📉 Visualisasi Histogram")
            fig, ax = plt.subplots()
            ax.hist(data, bins='auto', color='skyblue', edgecolor='black')
            ax.set_xlabel("Nilai")
            ax.set_ylabel("Frekuensi")
            ax.set_title("Histogram Data")
            st.pyplot(fig)

    except ValueError:
        st.error("Input tidak valid! Pastikan hanya memasukkan angka yang dipisahkan koma.")

if __name__ == "__main__":
    main()