# -*- coding: utf-8 -*-
"""Kalkulator Rata-Rata(1)

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10rX9gjWsCriPB7ZlZ1FvFdAGdgrg3U9C
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Konfigurasi tampilan halaman Streamlit
st.set_page_config(
    page_title="Kalkulator Rata-Rata dengan Grafik", # Judul yang muncul di tab browser
    page_icon=":bar_chart:",                       # Ikon yang muncul di tab browser
    layout="wide",                                 # Mengatur layout halaman menjadi lebar
)

# Judul utama aplikasi
st.title("📊 Kalkulator Rata-Rata Interaktif")

# Deskripsi singkat aplikasi menggunakan Markdown
st.markdown("Masukkan angka-angka yang dipisahkan dengan koma untuk menghitung rata-rata dan melihat visualisasinya dalam bentuk grafik batang.")
st.markdown("---") # Garis pemisah untuk estetika

# Input teks untuk memasukkan angka-angka
# Nilai default adalah "10, 20, 30"
input_angka = st.text_input("Masukkan Angka (pisahkan dengan koma):", "10, 20, 30")

# Tombol untuk memulai perhitungan dan menampilkan grafik
if st.button("Hitung & Tampilkan"):
    try:
        # Memisahkan string input berdasarkan koma, menghapus spasi ekstra, dan mengubahnya menjadi float
        angka_str = [x.strip() for x in input_angka.split(",")]
        # Menghapus elemen kosong yang mungkin muncul jika ada koma berlebih (misal "10,,20")
        angka = [float(x) for x in angka_str if x]

        # Memastikan ada angka yang dimasukkan sebelum menghitung rata-rata
        if not angka:
            st.error("❌ Tidak ada angka yang dimasukkan. Mohon masukkan setidaknya satu angka.")
        else:
            # Menghitung rata-rata
            rata_rata = sum(angka) / len(angka)

            # Menampilkan hasil rata-rata dengan pesan sukses
            st.success(f"✅ Rata-rata dari data yang dimasukkan adalah: **{rata_rata:.2f}**")
            st.markdown("---") # Garis pemisah

            # Membuat DataFrame Pandas dari angka-angka untuk keperluan plotting
            # 'Nilai' adalah kolom yang berisi angka, 'Indeks' adalah indeks untuk sumbu X
            df = pd.DataFrame({'Nilai': angka, 'Indeks': range(len(angka))})

            # Menampilkan subheader untuk bagian grafik
            st.subheader("Grafik Batang Data")

            # Membuat figure dan axes untuk plot Matplotlib
            fig, ax = plt.subplots(figsize=(10, 6)) # Ukuran figure yang lebih besar

            # Membuat grafik batang menggunakan Seaborn
            sns.barplot(x=df['Indeks'], y=df['Nilai'], palette="viridis", ax=ax) # Menggunakan palet warna "viridis"
            ax.set_xlabel("Indeks Data", fontsize=12) # Label sumbu X
            ax.set_ylabel("Nilai", fontsize=12)       # Label sumbu Y
            ax.set_title("Visualisasi Angka yang Anda Masukkan", fontsize=14, fontweight='bold') # Judul grafik

            # Menambahkan nilai di atas setiap batang (opsional, untuk informasi lebih lanjut)
            for p in ax.patches:
                ax.annotate(f'{p.get_height():.2f}', (p.get_x() + p.get_width() / 2., p.get_height()),
                            ha='center', va='center', xytext=(0, 5), textcoords='offset points', fontsize=10)

            # Menyesuaikan layout agar tidak ada tumpang tindih
            plt.tight_layout()

            # Menampilkan grafik di aplikasi Streamlit
            st.pyplot(fig)

    except ValueError:
        # Menangani error jika input tidak dapat diubah menjadi angka (non-numerik)
        st.error("❌ Input tidak valid. Pastikan Anda hanya memasukkan angka yang dipisahkan dengan koma.")
    except ZeroDivisionError:
        # Menangani error jika input angka kosong setelah pemrosesan
        st.error("❌ Tidak ada angka yang valid yang dimasukkan untuk dihitung.")
    except Exception as e:
        # Penanganan error umum untuk masalah lainnya
        st.error(f"Terjadi kesalahan: {e}")

st.markdown("---") # Garis pemisah
st.markdown("Dibuat dengan :heart: menggunakan Streamlit") # Footer aplikasi